### ISSUE TITLE
There is no 'ur5_macro.xacro' file.

### ISSUE THREAD

**Issue by sunnie-w** [DFKI-NI/mobipick#1]
I have error because I don't have 'ur5_macro.xacro' file in ur_description.
If this file is made by you, can you share this file also?
I want to test 'pick and place example'.

```
No such file or directory: /home/ait/ros_catkinws/src/universal_robot/ur_description/urdf/inc/ur5_macro.xacro
when processing file: /home/ait/ros_catkinws/src/mobipick/mobipick_description/urdf/mobipick/mobipick_v1_model.urdf.xacro

```

**Comment by mintar** [comment]
The `ur5_macro.xacro` was added in fmauch/universal_robot@580fd4a9480ec9fa33ca92b9e22b1423b3b8f350. Please update your https://github.com/fmauch/universal_robot.git package and make sure you're using the `calibration_devel` branch.
