### ISSUE TITLE
Rename "gripper_astra" to something more generic

### ISSUE THREAD

**Issue by brean** [DFKI-NI/mobipick#12]
1. We are using an Intel Realsense camera, so changing it from "astra" to something more generic would be good.
2. It's not a "gripper" so the name is misleading.

"main_camera" or "main_cam" would probably be better. It could also be split up some more so the image topic can for example be `main_camera/rgb/image_raw`instead of `gripper_astra/rgb/image_raw` while the tf-frame prefix can be something like "camera_mount" so it would be `camera_mount_rgb_optical_frame` instead of `gripper_astra_rgb_optical_frame`.

**Comment by mintar** [comment]
We've decided to do the renaming as follows in the Teams chat:

gripper_astra -> eef_main_cam
gripper_pico_flexx -> eef_forward_cam

**Comment by mintar** [comment]
I had to do the renaming in the following repos, so I just pushed them all without opening separate pull requests for each and every one:

```text
gazebo_logical_camera_plugin_ros
mobipick
mobipick-documentation.wiki
mobipick_labs
pbr_dope
pbr_mobipick_demo
pose_selector
```
